#include "globals.h"


uint32_t FrameCounter = 0;


uint16_t GameFlags[GAME_FLAG_COUNT] = {0};
uint16_t GameFlagsMax[GAME_FLAG_COUNT] = {
	1, //GAME_FLAG_FREEZE_CMDTS
	1, //GAME_FLAG_FORCE_WIREFRAME
	1, //GAME_FLAG_DISABLE_LIGHTING
	1, //GAME_FLAG_DISABLE_FOG
	1, //GAME_FLAG_DISABLE_LANTERN
	0, //GAME_FLAG_CURR_CMDTS
	0, //NULL
	0, //NULL
	1, //GAME_FLAG_PLAYER_INVINCIBLE
	1, //GAME_FLAG_ENEMY_INVINCIBLE
	1, //GAME_FLAG_FREE_CAM
	1, //GAME_FLAG_FREEZE_CAM
	0, //GAME_FLAG_CURRENT_LEVEL
};

